services:
  db:
    image: postgres:15-alpine
    container_name: lumatrace-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: lumatrace_db
    networks:
      - luma-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lumatrace_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: lumatrace-server
    ports:
      - "8082:8081"
    environment:
      - LUMATRACE_MASTER_KEY=4916120893041237898
      - SPRING_DATASOURCE_URL=jdbc:postgresql://lumatrace-postgres:5432/lumatrace_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - luma-net
    depends_on:
      db:
        condition: service_healthy
    restart: always

networks:
  luma-net:
    driver: bridge